# Generated by Django 3.2.1 on 2021-08-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteschedule",
            name="max_votes",
            field=models.SmallIntegerField(default=3),
        ),
    ]
