# Generated by Django 3.2.1 on 2021-08-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_voteschedule_max_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteschedule",
            name="is_test",
            field=models.BooleanField(default=True),
        ),
    ]
