# Generated by Django 3.2.1 on 2021-08-22 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_voteschedule_is_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vote.voteschedule",
                    ),
                ),
            ],
        ),
    ]
