# Generated by Django 3.2.1 on 2021-08-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0004_scoring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoring",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring",
                to="vote.voteschedule",
            ),
        ),
    ]
