# Generated by Django 3.2.1 on 2021-05-16 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_auto_20210516_0245"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="team",
        ),
        migrations.AddField(
            model_name="team",
            name="users",
            field=models.ManyToManyField(
                related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
