# Generated by Django 3.2.1 on 2021-06-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210516_0542"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="token",
        ),
    ]
