# Generated by Django 3.2.1 on 2021-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_team_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True, default="The best developer in the infinite universe."
            ),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="position",
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(blank=True, default="developer", max_length=128),
        ),
        migrations.DeleteModel(
            name="Position",
        ),
    ]
