"""
Django settings for devathon project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from .base import *

DEBUG = False

ALLOWED_HOSTS = []

CORS_ALLOW_ALL_ORIGINS = False
CORS_ORIGIN_WHITELIST = []

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USERNAME'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': '5432',
    }
}

MIDDLEWARE = [
    *MIDDLEWARE,
    'django.middleware.csrf.CsrfViewMiddleware'
]
