# Generated by Django 3.1.7 on 2021-07-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='sub_title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
