# Generated by Django 3.2.1 on 2021-07-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_demoimages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DemoImages",
            new_name="DemoImage",
        ),
    ]
