# Generated by Django 3.2.1 on 2021-08-16 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("demo", "0002_auto_20210815_0601"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="dislikers",
            field=models.ManyToManyField(
                related_name="disliked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="likers",
            field=models.ManyToManyField(
                related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
