# Generated by Django 3.2.1 on 2021-07-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_rename_demoimages_demoimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="demo",
            name="sub_title",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
