# Generated by Django 3.2.1 on 2021-08-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("demo", "0004_auto_20210816_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demo",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demo",
                to="accounts.team",
            ),
        ),
    ]
