# Generated by Django 3.2.1 on 2021-08-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0006_auto_20210819_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="demo",
            name="show",
            field=models.BooleanField(default=False),
        ),
    ]
