# Generated by Django 3.2.1 on 2021-08-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0007_demo_show"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demo",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
