# Generated by Django 3.2.1 on 2021-08-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0008_alter_demo_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demo",
            name="thumbnail",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
    ]
